# Generated by Django 3.2 on 2021-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_indexbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=256, verbose_name='商品价格'),
        ),
    ]
